version: '3.8'

services:
  validator_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validator_service
    restart: always
    volumes:
      - .:/validator_service
    environment:
      # use in code
      - CONFIG_FILE=product.yaml
    ports:
      - 8080:8080
    command: bash -c "cd src/validator_services && python3 main.py"

  node_cron_worker:
    build:
      context: .
      dockerfile: DockerCronfile
    container_name: node_cron_worker
    restart: always
    volumes:
      - .:/node_cron_worker
    command: bash -c "cd src/validator_services && python3 cron.py"